language: java

before_install: cd de.mik.timelog
install: mvn install 

addons:
  sonarcloud:
    organization: "michomat-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar